# Generated by Django 4.1.3 on 2022-11-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_bidproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='On Going', max_length=30),
        ),
    ]
