# Generated by Django 4.1.3 on 2022-11-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidproduct',
            name='addeddate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
